# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a1dec344f0dbd21c126f73349736805eaf7833c6b49c8d1ebe94e24302b8eac2ca0b7128fddd1d92f026187f6ef4008e34091e0c92a9f106b108a90d85159fc

test:
  secret_key_base: 47d630871abbe39aa338a21039f3b8f58e37b8b3c8096e45ebe52a6b4e7346ce31f26d8f0f92ecab38b5f43b0eecffa369c1104643ea5129904cf5662074ceb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
